services:

  nginx_proxy:
    container_name: wordle_nginx_proxy
    image: nginx:latest
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    restart: unless-stopped

  postgres:
    container_name: wordle_postgres
    image: postgres:latest
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
