services:

  nginx:
    container_name: wordle_nginx
    image: nginx:latest
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  postgres:
    container_name: wordle_postgres
    image: postgres:latest
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
