export {
  faGem,
} from '@fortawesome/free-regular-svg-icons'

export {
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowRotateRight,
  faBarsStaggered,
  faCaretDown,
  faCircleCheck,
  faCircleNotch,
  faCoins,
  faDeleteLeft,
  faEraser,
  faEye,
  faEyeSlash,
  faFire,
  faFireFlameSimple,
  faGem as fasGem,
  faHouse,
  faMinus,
  faPen,
  faPlus,
  faQuestion,
  faSquareFull,
  faStore,
  faTrash,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
