export {
  faArrowLeft,
  faArrowRight,
  faCaretDown,
  faCircleCheck,
  faCircleNotch,
  faCoins,
  faDeleteLeft,
  faDollarSign,
  faEraser,
  faFire,
  faHouse,
  faQuestion,
  faStore,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
